version: 2
jobs:
  build:
    docker:
    # Prim image that all the "work is done on"
    - image: circleci/golang:latest
      
    steps:
      - checkout
      - run: |
          echo "Circle Compare URL: " $CIRCLE_COMPARE_URL
          COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
          echo "Commit range: " $COMMIT_RANGE
          git diff $COMMIT_RANGE --name-status
      - run: |
          for dir in $(git log --name-only --oneline -1 | sed 1d | grep '/' | cut -d "/" -f1 | sed '/^\.circleci$/d' | sort -u); do $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ); done